Feature/apollo typescript setup
indigotech/onboard-william-fukushima-backend pull request #6
Opened 2021-05-18 14:20 UTC by williamfukushima

Added Apollo and Typescript setup

2021-05-18 17:14 UTC, alanraso requested changes
Pro setup do Typescript ficou faltando algumas coisas: o `tsconfig` que é bem importante nos projetos Typescript, e a dependencia npm `typescript` (devDependency)

Um "nice to have" tbm é ter o `ts-node` pra você poder rodar o server como se você tivesse "compilando" o typescript.

2021-05-18 17:14 UTC, alanraso commented on server.tsx
> +const { ApolloServer, gql } = require('apollo-server');
`tsx` é só pra react. Aqui pode ser `ts` mesmo.

2021-05-18 17:14 UTC, alanraso commented on package.json
> +  },
Como vc rodou o servidor pra testar?

2021-05-18 17:14 UTC, alanraso commented on server.tsx
> +const { ApolloServer, gql } = require('apollo-server');
Com a adoção do Typescript, vc poderia excluir aquele `server.js` né? A partir de agora podemos programar apenas em Typescript.

2021-05-18 18:29 UTC, williamfukushima commented on package.json
> +  },
node server.tsx

2021-05-18 19:03 UTC, RiczCalixto commented on package.json
> +    "apollo-server": "^2.24.0",
Seria interessante remover o ^ para fixar a versão da lib.

2021-05-18 19:24 UTC, alanraso commented on package.json
> +  },
Pra rodar direto com node e dar certo tem bastante coisa que precisaria não estar acontecendo. Import de outros arquivos, por exemplo, daria problema. No geral a gente costuma usar dois scripts para inicializar o servidor:

1. `npm run dev`: um script que seria mais pra testar mesmo. Geralmente usamos `ts-node-dev`, `nodemon` ou algum outro pacote que detecta mudanças no código e re-roda automaticamente

2. `npm start`: geralmente esse seria o "start" do servidor no ambiente de produção, então usamos `node` mesmo, mas rodamos o código já transpilado do Typescript (e, portanto, código Javascript) de outra pasta análoga ao código fonte. O tsconfig centraliza algumas configurações pra esse build. Dá uma olhada em algum tutorial na internet que tenha algo desse tipo.

2021-05-18 20:06 UTC, williamfukushima reviewed
Feito nos ultimos commits

2021-05-19 11:48 UTC, alanraso approved these changes

2021-05-19 13:26 UTC, merged